name: Build PDF from Markdown

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          sudo apt-get install -y texlive-xetex

      - name: Create and activate virtual environment
        run: |
          python -m pip install virtualenv
          python -m virtualenv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .

      - name: Generate PDF
        run: |
          swent_prd generate --team 2 template

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v3
        with:
          name: PRD-PDF
          path: Team_2_prd.pdf
